/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param message 
 * @param time 
 * @param uptime 
 */


data class Health (

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "time")
    val time: kotlin.String,

    @Json(name = "uptime")
    val uptime: kotlin.Double

)

