/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: oneToMany,manyToOne,oneToOne
 */

enum class RelationType(val value: kotlin.String) {

    @Json(name = "oneToMany")
    oneToMany("oneToMany"),

    @Json(name = "manyToOne")
    manyToOne("manyToOne"),

    @Json(name = "oneToOne")
    oneToOne("oneToOne");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RelationType) "$data" else null

        /**
         * Returns a valid [RelationType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RelationType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

