/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param entity 
 * @param rows 
 */


data class SchemaDataEntity (

    @Json(name = "entity")
    val entity: kotlin.String,

    @Json(name = "rows")
    val rows: kotlin.collections.List<kotlin.Any>

)

