/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param dialect 
 * @param mapping 
 * @param connection 
 */


data class DataSource (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "dialect")
    val dialect: kotlin.String,

    @Json(name = "mapping")
    val mapping: kotlin.String,

    @Json(name = "connection")
    val connection: kotlin.Any?

)

