/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model

import io.github.flaviolionelrita.lambdaorm.client.model.EnumValue

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param propertyValues 
 */


data class Enum (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "values")
    val propertyValues: kotlin.collections.List<EnumValue>

)

