/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param fields 
 */


data class Index (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "fields")
    val fields: kotlin.collections.List<kotlin.String>

)

