/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.flaviolionelrita.lambdaorm.client.model

import io.github.flaviolionelrita.lambdaorm.client.model.SchemaDataEntity

import com.squareup.moshi.Json

/**
 * 
 *
 * @param entities 
 */


data class SchemaData (

    @Json(name = "entities")
    val entities: kotlin.collections.List<SchemaDataEntity>

)

