/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model

import org.flaviolrita.lambdaorm.model.Relation

import com.squareup.moshi.Json

/**
 * 
 *
 * @param entity 
 * @param relation 
 */


data class Dependent (

    @Json(name = "entity")
    val entity: kotlin.String,

    @Json(name = "relation")
    val relation: Relation

)

