/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model

import org.flaviolrita.lambdaorm.model.EntityMapping

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param entities 
 * @param extends 
 * @param mapping 
 */


data class Mapping (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "entities")
    val entities: kotlin.collections.List<EntityMapping>,

    @Json(name = "extends")
    val extends: kotlin.String? = null,

    @Json(name = "mapping")
    val mapping: kotlin.String? = null

)

