/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model

import org.flaviolrita.lambdaorm.model.Parameter
import org.flaviolrita.lambdaorm.model.Property
import org.flaviolrita.lambdaorm.model.Relation

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param type 
 * @param entity 
 * @param children 
 * @param fields 
 * @param `property` 
 * @param parameters 
 * @param relation 
 * @param sentence 
 * @param alias 
 * @param number 
 */


data class Metadata (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "entity")
    val entity: kotlin.String? = null,

    @Json(name = "children")
    val children: kotlin.collections.List<Metadata>? = null,

    @Json(name = "fields")
    val fields: kotlin.collections.List<Property>? = null,

    @Json(name = "property")
    val `property`: kotlin.String? = null,

    @Json(name = "parameters")
    val parameters: kotlin.collections.List<Parameter>? = null,

    @Json(name = "relation")
    val relation: Relation? = null,

    @Json(name = "sentence")
    val sentence: kotlin.String? = null,

    @Json(name = "alias")
    val alias: kotlin.String? = null,

    @Json(name = "number")
    val number: kotlin.Double? = null

)

