/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param entity 
 * @param dialect 
 * @param dataSource 
 * @param sentence 
 * @param childs 
 */


data class MetadataSentence (

    @Json(name = "entity")
    val entity: kotlin.String,

    @Json(name = "dialect")
    val dialect: kotlin.String,

    @Json(name = "dataSource")
    val dataSource: kotlin.String,

    @Json(name = "sentence")
    val sentence: kotlin.String,

    @Json(name = "childs")
    val childs: kotlin.collections.List<MetadataSentence>? = null

)

