/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param message 
 * @param time 
 */


data class Ping (

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "time")
    val time: kotlin.String

)

