/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param result 
 */


data class QueryResponse (

    @Json(name = "result")
    val result: kotlin.Any?

)

