/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model

import org.flaviolrita.lambdaorm.model.RelationType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param type 
 * @param from 
 * @param entity 
 * @param to 
 * @param composite 
 * @param weak 
 * @param target 
 * @param targetComposite 
 */


data class Relation (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "type")
    val type: RelationType,

    @Json(name = "from")
    val from: kotlin.String,

    @Json(name = "entity")
    val entity: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "composite")
    val composite: kotlin.Boolean? = null,

    @Json(name = "weak")
    val weak: kotlin.Boolean? = null,

    @Json(name = "target")
    val target: kotlin.String? = null,

    @Json(name = "targetComposite")
    val targetComposite: kotlin.Boolean? = null

)

