/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.flaviolrita.lambdaorm.model

import org.flaviolrita.lambdaorm.model.RuleDataSource

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param dataSources 
 */


data class Stage (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "dataSources")
    val dataSources: kotlin.collections.List<RuleDataSource>

)

